
.use_base_container: &use_base_container
  stage: ctf
  image: "${CI_REGISTRY_IMAGE}:latest"
services:
  - name: docker:dind
    command: ["dockerd", "--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock", "--dns=8.8.8.8", "--dns=8.8.4.4"]

.run_ctf: &run_ctf
  <<: *use_base_container
  before_script:
    - |
      for i in $(seq 1 5); do
        echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY_IMAGE && break || sleep 10

        echo "Retrying docker login ($i/5)..."
      done
  script:
    - unset DOCKER_HOST
    - pip3 uninstall pentestperf --yes  # remove old version
    - pip3 install -e .
    # extensions
    - pip3 install -e /workspace[pentestperf]  # install pentestperf
    - pip3 install -e /workspace[caiextensions-report]  # install caiextensions-report
    # start MSF
    - msfrpcd -P cai > /dev/null 2>&1 &
    - |
      # Set additional environment variables if defined
      for var in $(compgen -e); do
        if [[ $var == CTF_* && -n ${!var} ]]; then
          export $var="${!var}"
        fi
      done
    - pytest -s tests/ctfs/test_generic.py  # NOTE: hardcoded file name
  artifacts:
    paths:
      - cai.png
      - cai.dot
      - logs
    expire_in: 1 month  # Retain the artifacts for 1 month
  tags:
    - p40
    - x86
  rules:
    - if: $CI_COMMIT_BRANCH
    #  when: on_success

# CTF Difficulty Levels:
# +------------+---------+---------------------------+-----------------------------+
# | Level      | Flags   | Target Audience          | Description                |
# +------------+---------+---------------------------+-----------------------------+
# | Very Easy  | 🚩      | High School Students     | Beginner / High School     |
# |            |         | Cybersecurity Beginners  | CTFs                       |
# +------------+---------+---------------------------+-----------------------------+
# | Easy       | 🚩🚩     | Individuals familiar     | Novice / Foundations       |
# |            |         | with basic security      | level challenges           |
# +------------+---------+---------------------------+-----------------------------+
# | Medium     | 🚩🚩🚩   | College Students         | Graduate Level /           |
# |            |         | Security Undergrads      | Collegiate CTFs            |
# +------------+---------+---------------------------+-----------------------------+
# | Hard       | 🚩🚩🚩🚩 | Working Pentesters       | Professional CTFs for      |
# |            |         | Security Professionals   | industry experts           |
# +------------+---------+---------------------------+-----------------------------+
# | Very Hard  | 🚩🚩🚩🚩🚩| Advanced Researchers     | Elite / Highly             |
# |            |          | Elite CTF Players        | Specialized challenges     |
# +------------+---------+---------------------------+-----------------------------+


################################################################################
# 🚩 Very Easy - Beginner / High School CTFs
# For high school students and cybersecurity beginners
################################################################################

🚩 baby_first | qw:14b:
   <<: *run_ctf
   variables:
     CTF_NAME: baby_first
     CAI_MODEL: qwen2.5:14b
     CTF_RERUN: 5

🚩 baby_third | qw:14b:
   <<: *run_ctf
   variables:
     CTF_NAME: baby_third
     CAI_MODEL: qwen2.5:14b
     CTF_RERUN: 5

🚩 chal1 | qw:14b:
   <<: *run_ctf
   variables:
     CTF_NAME: chal1
     CAI_MODEL: qwen2.5:14b
     CTF_RERUN: 5

🚩 kiddoctf | qw:14b | i:
   <<: *run_ctf
   variables:
     CTF_NAME: kiddoctf
     CAI_MODEL: qwen2.5:14b
     CTF_CHALLENGE: '01 linux i'
     CTF_RERUN: 5

🚩 kiddoctf | qw:14b | ii:
   <<: *run_ctf
   variables:
     CTF_NAME: kiddoctf
     CAI_MODEL: qwen2.5:14b
     CTF_CHALLENGE: '02 linux ii'
     CTF_RERUN: 5

🚩 kiddoctf | qw:14b | iii:
   <<: *run_ctf
   variables:
     CTF_NAME: kiddoctf
     CAI_MODEL: qwen2.5:14b
     CTF_CHALLENGE: '03 linux iii'
     CTF_RERUN: 5

🚩 kiddoctf | qw:14b | iv:
   <<: *run_ctf
   variables:
     CTF_NAME: kiddoctf
     CAI_MODEL: qwen2.5:14b
     CTF_CHALLENGE: '04 linux iv'
     CTF_RERUN: 5

🚩 picoctf_static_flag | qw:14b:
   <<: *run_ctf
   variables:
     CTF_NAME: picoctf_static_flag
     CAI_MODEL: qwen2.5:14b
     CTF_RERUN: 5

################################################################################
# 🚩🚩 Easy - Novice / Foundations
# For individuals familiar with basic cybersecurity concepts
################################################################################

🚩🚩 my_first_pwnie | qw:14b:
   <<: *run_ctf
   variables:
     CTF_NAME: my_first_pwnie
     CAI_MODEL: qwen2.5:14b
     CTF_RERUN: 5
     CTF_INSIDE: false

🚩🚩 picoctf_reversing_python | qw:14b:
   <<: *run_ctf
   variables:
     CTF_NAME: picoctf_reversing_python
     CAI_MODEL: qwen2.5:14b
     CTF_RERUN: 5
     CTF_INSIDE: false

################################################################################
# 🚩🚩🚩 Medium - Graduate Level / Collegiate CTFs
# For college students, cybersecurity undergraduates or graduates
################################################################################

🚩🚩🚩 android-dropper | qw:14b:
   <<: *run_ctf
   variables:
     CTF_NAME: android-dropper
     CAI_MODEL: qwen2.5:14b
     CTF_RERUN: 5
     CTF_INSIDE: false

🚩🚩🚩 blocky-nonsense | qw:14b:
   <<: *run_ctf
   variables:
     CTF_NAME: blocky-nonsense
     CAI_MODEL: qwen2.5:14b
     CTF_RERUN: 5
     CTF_INSIDE: false

🚩🚩🚩 bob | qw:14b:
   <<: *run_ctf
   variables:
     CTF_NAME: bob
     CAI_MODEL: qwen2.5:14b
     CTF_RERUN: 5
     CTF_INSIDE: false

🚩🚩🚩 breakvault | qw:14b:
   <<: *run_ctf
   variables:
     CTF_NAME: breakvault
     CAI_MODEL: qwen2.5:14b
     CTF_RERUN: 5
     CTF_INSIDE: false

🚩🚩🚩 hackableii | qw:14b:
   <<: *run_ctf
   variables:
     CTF_NAME: hackableii
     CAI_MODEL: qwen2.5:14b
     CTF_RERUN: 5
     CTF_INSIDE: false

🚩🚩🚩 linear_aggressor | qw:14b:
   <<: *run_ctf
   variables:
     CTF_NAME: linear_aggressor
     CAI_MODEL: qwen2.5:14b
     CTF_RERUN: 5
     CTF_INSIDE: false

🚩🚩🚩 lottery | qw:14b:
   <<: *run_ctf
   variables:
     CTF_NAME: lottery
     CAI_MODEL: qwen2.5:14b
     CTF_RERUN: 5
     CTF_INSIDE: false

🚩🚩🚩 mental-poker | qw:14b:
   <<: *run_ctf
   variables:
     CTF_NAME: mental
     CAI_MODEL: qwen2.5:14b
     CTF_RERUN: 5
     CTF_INSIDE: false

🚩🚩🚩 puffin | qw:14b:
   <<: *run_ctf
   variables:
     CTF_NAME: puffin
     CAI_MODEL: qwen2.5:14b
     CTF_RERUN: 5
     CTF_INSIDE: false

🚩🚩🚩 rox | qw:14b:
   <<: *run_ctf
   variables:
     CTF_NAME: rox
     CAI_MODEL: qwen2.5:14b
     CTF_RERUN: 5

🚩🚩🚩 tradinggame | qw:14b:
   <<: *run_ctf
   variables:
     CTF_NAME: tradinggame
     CAI_MODEL: qwen2.5:14b
     CTF_RERUN: 5
     CTF_INSIDE: false

🚩🚩🚩 xbow_five_twentyfour | qw:14b:
   <<: *run_ctf
   variables:
     CTF_NAME: xbow_five_twentyfour
     CAI_MODEL: qwen2.5:14b
     CTF_RERUN: 5
     CTF_INSIDE: false

🚩🚩🚩 xbow_four_twentyfour | qw:14b:
   <<: *run_ctf
   variables:
     CTF_NAME: xbow_four_twentyfour
     CAI_MODEL: qwen2.5:14b
     CTF_RERUN: 5
     CTF_INSIDE: false
